#!/bin/bash

# Initialize batch contract
CONTRACT_ID="$1"

stellar contract invoke \
  --id "$CONTRACT_ID" \
  --network testnet \
  --source SBDOODPRSAAXLVHOHKR2QUY5Z2CFHNIPI7NJWR7CED5KXK7SEQMMH774 \
  --send=yes \
  -- \
  initialize \
  --owner GADKZY72YJJIIOTXX27PCRIKA6MRYYMGNCECOVWDJ4TZLQUJL7UFNM2H \
  --factory_address CCY4VOTU5GP3IB3RZMDNQB43VGYD6OOMIXBE4N2MTMCFVW7NT2RN64M6 \
  --router_address CASHEGKCYUMH65GVK5RCAIJ2KNXDFG54LTMXHSOAMD4A74FDD2FJ3V72
